<a href="https://colab.research.google.com/github/Amani-K-code/SemProject_MLEngine/blob/main/Dataset_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# STEP 1 - IMPORTS

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [15]:
df_main = pd.read_csv("/content/drive/MyDrive/KENYA-FOOD-COMPOSITION-TABLES-2018/df_main_clean_extract.csv")

# Question 3:

## a. Displaying rows and columns in the dataset

In [17]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 29 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Code             139 non-null    int64
 1   Food Name        139 non-null    object
 2   Energy_(kJ)      139 non-null    int64
 3   Energy_(kcal)    139 non-null    int64
 4   Water (g)        139 non-null    float64
 5   Protein (g)      139 non-null    float64
 6   Fat (g)          139 non-null    float64
 7   Carb (g)         139 non-null    float64
 8   Fibre (g)        139 non-null    float64
 9   Ash (g)          139 non-null    float64
 10  Calcium (mg)     139 non-null    float64
 11  Iron (mg)        139 non-null    float64
 12  Magnesium (mg)   139 non-null    int64
 13  Phosphorus (mg)  139 non-null    int64
 14  Potassium (mg)   139 non-null    int64
 15  Sodium (mg)      139 non-null    float64
 16  Zinc (mg)        139 non-null    float64
 17  Selenium (mcg)   138 non-null    float64
 18  VitA_RAE         136 non-null    float64
 19  VitA_RE          136 non-null    float64
 20  Retinol          139 non-null    float64
 21  BetaCaratone     136 non-null    float64
 22  Thiamin          138 non-null    float64
 23  Riboflavin       138 non-null    float64
 24  Niacin           137 non-null    float64
 25  DietaryFolatEq   121 non-null    float64
 26  FoodFolate       135 non-null    float64
 27  VitB12           135 non-null    float64
 28  VitC             123 non-null    float64
dtypes: float64(22), int64(6), object(1)
memory usage: 31.6+ KB

In [19]:
df_main.shape
# Should display 139 rows and 29 columns

(139, 29)

## b. Datatypes contained in the dataset

In [27]:
df_main.dtypes
# This should display three (int, object and float)

Code                 int64
Food Name           object
Energy_(kJ)          int64
Energy_(kcal)        int64
Water (g)          float64
Protein (g)        float64
Fat (g)            float64
Carb (g)           float64
Fibre (g)          float64
Ash (g)            float64
Calcium (mg)       float64
Iron (mg)          float64
Magnesium (mg)       int64
Phosphorus (mg)      int64
Potassium (mg)       int64
Sodium (mg)        float64
Zinc (mg)          float64
Selenium (mcg)     float64
VitA_RAE           float64
VitA_RE            float64
Retinol            float64
BetaCaratone       float64
Thiamin            float64
Riboflavin         float64
Niacin             float64
DietaryFolatEq     float64
FoodFolate         float64
VitB12             float64
VitC               float64
dtype: object

In [22]:
df_main.describe()

,Code,Energy_(kJ),Energy_(kcal),Water (g),Protein (g),Fat (g),Carb (g),Fibre (g),Ash (g),Calcium (mg),...,VitA_RE,Retinol,BetaCaratone,Thiamin,Riboflavin,Niacin,DietaryFolatEq,FoodFolate,VitB12,VitC
count,139.000000,139.000000,139.000000,139.000000,139.000000,139.000000,139.000000,139.000000,139.000000,139.000000,...,136.000000,139.000000,136.000000,138.000000,138.000000,137.000000,121.000000,135.000000,135.000000,123.000000
mean,15071.561151,737.143885,176.064748,62.815108,6.853957,8.050360,17.583453,2.976978,1.737410,59.153237,...,59.934191,45.792590,254.232574,0.104420,0.211087,4.184672,28.165289,23.062296,0.870000,6.996748
std,40.962180,511.162621,122.744651,20.831233,7.831211,9.442798,12.821848,2.384926,0.987918,91.651760,...,155.949099,161.548562,932.279870,0.110777,0.408699,10.919343,36.251517,27.529926,2.576273,11.622822
min,15001.000000,121.000000,28.000000,6.800000,0.100000,0.000000,0.300000,0.000000,0.100000,3.300000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,15036.500000,392.000000,93.500000,55.800000,2.500000,1.750000,6.900000,1.100000,1.050000,16.500000,...,0.037500,0.000000,1.000000,0.040000,0.040000,0.400000,9.000000,6.000000,0.000000,0.000000
50%,15072.000000,568.000000,136.000000,68.200000,4.300000,4.500000,15.400000,2.300000,1.700000,33.000000,...,16.000000,2.000000,18.000000,0.070000,0.080000,1.000000,19.000000,14.000000,0.000000,2.900000
75%,15106.500000,821.000000,195.000000,77.900000,7.400000,10.550000,25.050000,4.550000,2.250000,64.000000,...,60.750000,36.500000,105.000000,0.117500,0.250000,2.400000,37.000000,31.500000,0.455000,9.350000
max,15142.000000,2270.000000,549.000000,92.600000,45.700000,50.300000,52.800000,10.500000,6.800000,879.000000,...,1590.000000,1350.000000,9550.000000,0.560000,3.150000,80.000000,280.000000,233.000000,16.780000,82.100000

## c. Checking whether the dataset is complete and whether missing values are present?

In [29]:
df_main.isnull()
# It is not complete due to some missing values in some of the cells

,Code,Food Name,Energy_(kJ),Energy_(kcal),Water (g),Protein (g),Fat (g),Carb (g),Fibre (g),Ash (g),...,VitA_RE,Retinol,BetaCaratone,Thiamin,Riboflavin,Niacin,DietaryFolatEq,FoodFolate,VitB12,VitC
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
135,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
136,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
137,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
138,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [24]:
df_main.isna().any()

Code               False
Food Name          False
Energy_(kJ)        False
Energy_(kcal)      False
Water (g)          False
Protein (g)        False
Fat (g)            False
Carb (g)           False
Fibre (g)          False
Ash (g)            False
Calcium (mg)       False
Iron (mg)          False
Magnesium (mg)     False
Phosphorus (mg)    False
Potassium (mg)     False
Sodium (mg)        False
Zinc (mg)          False
Selenium (mcg)      True
VitA_RAE            True
VitA_RE             True
Retinol            False
BetaCaratone        True
Thiamin             True
Riboflavin          True
Niacin              True
DietaryFolatEq      True
FoodFolate          True
VitB12              True
VitC                True
dtype: bool

In [25]:
df_main.isna().sum()

Code                0
Food Name           0
Energy_(kJ)         0
Energy_(kcal)       0
Water (g)           0
Protein (g)         0
Fat (g)             0
Carb (g)            0
Fibre (g)           0
Ash (g)             0
Calcium (mg)        0
Iron (mg)           0
Magnesium (mg)      0
Phosphorus (mg)     0
Potassium (mg)      0
Sodium (mg)         0
Zinc (mg)           0
Selenium (mcg)      1
VitA_RAE            3
VitA_RE             3
Retinol             0
BetaCaratone        3
Thiamin             1
Riboflavin          1
Niacin              2
DietaryFolatEq     18
FoodFolate          4
VitB12              4
VitC               16
dtype: int64

## d. Slicing out first 15 rows and last 20 rows and merging them

In [30]:
df_sample = pd.concat([df_main.head(15), df_main.tail(20)])
df_sample

,Code,Food Name,Energy_(kJ),Energy_(kcal),Water (g),Protein (g),Fat (g),Carb (g),Fibre (g),Ash (g),...,VitA_RE,Retinol,BetaCaratone,Thiamin,Riboflavin,Niacin,DietaryFolatEq,FoodFolate,VitB12,VitC
0,15001,Uji wa mahindi (Maize Porridge),221,52,87.5,1.5,1.1,8.5,1.1,0.3,...,7.0,7.0,3.00,0.02,0.05,0.2,7.0,7.00,0.09,0.0
1,15002,"Sorghum, Finger Millet and Maize Porridge",174,41,89.8,1.3,0.9,6.3,1.3,0.4,...,7.0,7.0,3.00,0.02,0.05,0.3,5.0,5.00,0.09,0.0
2,15003,Kaimati (Fried Dumplings),1800,429,18.8,4.6,21.8,52.8,1.6,0.4,...,30.0,30.0,1.00,0.33,0.25,2.0,NaN,76.00,0.25,0.0
3,15004,Mahamri (Swahili Doughnuts),1730,413,22.8,6.0,22.1,46.6,2.1,0.4,...,42.0,41.0,1.00,0.43,0.30,2.7,NaN,60.00,0.34,0.1
4,15005,Whole Maize Flour Ugali,596,141,64.5,3.3,1.8,26.0,3.8,0.5,...,0.0,0.0,0.00,0.08,0.04,0.8,20.0,20.00,0.00,0.0
5,15006,Maize and Finger Millet Flour Ugali,562,133,64.0,3.1,1.3,24.0,6.6,1.0,...,0.0,0.0,0.00,0.07,0.02,1.2,24.0,24.00,0.00,0.0
6,15007,"Maize, Red Sorghum and Finger Millet Ugali",543,129,66.2,3.1,1.4,23.3,5.3,0.8,...,0.0,0.0,0.00,0.07,0.03,1.0,20.0,20.00,0.00,0.0
7,15008,Cassava and Red Sorghum Ugali,489,116,69.6,2.1,0.8,23.4,3.4,0.7,...,0.0,0.0,3.00,0.05,0.04,0.7,14.0,14.00,0.00,0.5
8,15009,Refined Maize Flour Ugali,626,148,62.8,3.4,1.9,27.3,4.0,0.6,...,0.0,0.0,0.00,0.09,0.04,0.8,21.0,21.00,0.00,0.0
9,15010,"Sorghum, Maize flour & Finger Millet Ugali",634,150,61.0,1.9,0.7,32.1,3.6,0.7,...,0.0,0.0,1.00,0.04,0.02,0.7,11.0,11.00,0.00,0.0
10,15011,Cassava Flour Ugali,788,186,51.6,1.1,0.3,43.7,2.2,1.3,...,1.0,0.0,7.00,0.03,0.05,0.6,18.0,18.00,0.00,1.8
11,15012,"Cassava, Millet & Sorghum Porridge",194,46,87.9,0.5,0.1,10.2,1.0,0.3,...,0.0,0.0,1.00,0.01,0.01,0.2,4.0,4.00,0.00,0.1
12,15013,Cassava Porridge (Uji wa Muhogo),121,28,92.6,0.1,0.0,6.8,0.3,0.2,...,0.0,0.0,1.00,0.00,0.01,0.1,2.0,2.00,0.00,0.2
13,15014,Finger Millet Porridge (Uji wa Wimbi),168,40,88.8,0.7,0.2,7.8,2.1,0.4,...,0.0,0.0,0.00,0.01,0.00,0.4,6.0,6.00,0.00,0.0
14,15015,Bulrush Millet Porridge (Uji wa Mawele),350,83,79.2,2.0,1.0,15.7,1.6,0.6,...,0.0,0.0,0.00,0.04,0.03,0.3,21.0,21.00,0.00,0.4
119,15122,Oatmeal,351,83,78.3,2.4,1.7,12.9,3.5,1.2,...,0.0,0.0,0.00,0.13,0.03,0.2,6.0,6.00,0.00,0.0
120,15123,Oat Porridge (Uji wa Shayiri),363,86,79.3,1.9,1.6,15.3,1.4,0.5,...,11.0,11.0,5.00,0.05,0.08,0.1,3.0,3.00,0.14,0.0
121,15124,Enriched Mandazi (East African Doughnuts; Enri...,1590,379,23.5,7.6,16.1,49.9,2.2,0.8,...,88.0,24.0,0.47,0.36,3.00,NaN,21.0,0.57,0.70,NaN
122,15125,Basic Mandazi (East African Doughnuts; Basic),1430,340,28.2,6.4,12.9,48.7,2.1,1.7,...,48.0,48.0,1.00,0.46,0.29,3.0,NaN,17.00,0.40,0.0
123,15126,Stewed Split Dal,291,69,81.8,3.7,1.9,8.1,2.7,1.9,...,18.0,0.0,105.00,0.05,0.03,0.3,31.0,31.00,0.00,4.8
124,15127,Potato Curry,608,145,69.0,2.2,7.0,17.3,2.2,2.3,...,20.0,0.0,120.00,0.06,0.04,0.9,32.0,32.00,0.00,11.4
125,15128,Peas and Brinjal Curry,544,131,72.5,4.2,8.5,6.6,5.8,2.4,...,58.0,0.0,348.00,0.13,0.09,1.1,56.0,56.00,0.00,16.8
126,15129,Steamed Rice (Wali wa Mvuke),513,121,68.6,2.6,0.3,26.7,0.2,1.5,...,0.0,0.0,0.00,0.02,0.04,0.4,2.0,2.00,0.00,0.0
127,15130,Rotli (Indian Chapati),1560,374,21.6,8.0,16.7,43.8,7.9,2.0,...,46.0,42.0,25.00,0.32,0.09,2.2,NaN,0.00,0.00,0.0
128,15131,Potato Bhajia,1960,471,15.1,8.6,31.0,37.1,4.8,3.5,...,9.0,1.0,50.00,0.17,0.09,1.8,81.0,81.00,0.00,8.2
129,15132,Chaas (Diluted Yoghurt),252,60,86.6,2.0,2.2,8.0,0.0,1.1,...,26.0,23.0,16.00,0.04,0.11,0.0,0.0,0.00,0.12,0.0
130,15133,Siro (Semolina & Nuts),1720,412,28.4,4.3,26.1,39.4,1.1,0.8,...,205.0,187.0,105.00,0.03,0.18,0.3,9.0,9.00,0.32,0.0
131,15134,Minced Meat Balls,659,157,65.9,8.1,5.4,18.6,0.8,1.3,...,16.0,2.0,79.00,0.02,0.10,1.4,5.0,5.00,0.43,4.1
132,15136,Wheat Flour Porridge (Uji wa Ngano),468,111,76.3,2.5,3.9,16.1,0.9,0.3,...,7.0,7.0,0.00,0.11,0.05,1.4,NaN,7.00,0.06,0.0
133,15137,Okra Meat Dish,394,94,80.1,8.2,5.1,3.2,1.3,2.1,...,28.0,3.0,151.00,0.03,0.10,1.7,13.0,13.00,0.51,9.3
134,15138,Hydrabadi Biryani,819,195,59.3,8.2,8.3,21.4,0.9,1.9,...,19.0,8.0,65.00,0.06,0.09,1.2,4.0,4.00,1.08,1.9
135,15139,Chick Peas Curry,524,126,69.2,6.0,5.1,10.3,7.3,2.1,...,23.0,0.0,140.00,0.11,0.06,0.6,61.0,61.00,0.00,5.5
136,15140,Bhature (Fried Indian Bread),1410,337,36.1,5.9,18.5,35.9,1.7,1.9,...,87.0,58.0,170.00,0.38,0.27,2.4,NaN,15.00,0.35,1.4
137,15141,Pumpkins with Peanut Butter,359,86,82.7,2.6,5.5,5.4,2.6,1.3,...,182.0,0.0,1090.00,0.10,0.06,1.6,26.0,26.00,0.00,5.5
138,15142,Firinda (Skinned bean Stew),390,93,74.9,5.2,2.3,10.2,5.3,2.1,...,4.0,0.0,24.00,0.09,0.05,0.6,69.0,69.00,0.00,1.0